<a href="https://colab.research.google.com/github/noorulcodes/login-system/blob/main/numpy%20functions%20(basics).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **NUMPY**

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array((34,45,56))

array([34, 45, 56])

In [5]:
np.array([3,4,5], "complex")

array([3.+0.j, 4.+0.j, 5.+0.j])

In [12]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [6]:
np.arange(2,20,2,dtype = "float")

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [28]:
np.arange(2,20,7, dtype = 'int')

array([ 2,  9, 16])

In [9]:
np.arange(15,1,-1)

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [11]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [10]:
np.zeros(3,dtype = "int")

array([0, 0, 0])

In [13]:
np.zeros((2,3), dtype = "int")

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
np.ones((3,4), dtype = 'int', order = 'c')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
np.ones((3,4), dtype = 'int', order = 'F')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this 

In [16]:
np.empty((2,3), dtype = 'int')

array([[28087648,        0,        0],
       [       0,        0,        0]])

In [1]:
import numpy as np
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [19]:
np.empty((3,3), dtype = 'int')

array([[4611686018427387904, 4616189618054758400, 4618441417868443648],
       [4620693217682128896, 4621819117588971520, 4622945017495814144],
       [4624070917402656768, 4625196817309499392, 4625759767262920704]])

In [20]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [21]:
np.linspace(2,3,num = 5, retstep = True, endpoint = True) #output with returnstep 0.25 and endpoint 3

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [25]:
np.linspace(1,20, num = 10, endpoint = True, retstep = True)

(array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
        11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ]),
 2.111111111111111)

In [26]:
np.linspace(2,20, num = 5)

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [27]:
np.linspace(1,100,num = 10, retstep= True, endpoint = False) # endvalue 100 not included

(array([ 1. , 10.9, 20.8, 30.7, 40.6, 50.5, 60.4, 70.3, 80.2, 90.1]), 9.9)

In [29]:
np.linspace(2,20, dtype= 'int') # num of values is 50 as default, if num = 10, then an array contain 10 values 

array([ 2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  6,  6,  6,  7,  7,  7,
        8,  8,  8,  9,  9, 10, 10, 10, 11, 11, 11, 12, 12, 13, 13, 13, 14,
       14, 14, 15, 15, 15, 16, 16, 17, 17, 17, 18, 18, 18, 19, 19, 20])

In [32]:
np.random.rand(4,3)

array([[0.70036526, 0.75669579, 0.69203525],
       [0.15601171, 0.97597646, 0.1529844 ],
       [0.9802251 , 0.84566191, 0.55814626],
       [0.02456447, 0.95830457, 0.36924966]])

In [33]:
np.random.randn(5)

array([-0.59211878, -1.01800271,  2.17947585, -0.18013282,  0.43706311])

In [34]:
np.random.randn(3,5)

array([[-1.12501833, -2.17270051,  0.64137721, -1.55214627, -0.57499045],
       [-0.49084552, -0.71331031,  0.99683348,  0.09189527,  0.50277185],
       [-0.73996075,  1.41901921,  0.90380395, -0.42294865,  0.28259526]])

In [37]:
np.random.ranf(5)

array([0.55300312, 0.92762546, 0.30193079, 0.12110098, 0.88814318])

In [44]:
np.random.ranf(3)

array([0.1716179 , 0.6629275 , 0.21014386])

In [46]:
help(np.random.random_sample)

Help on built-in function random_sample:

random_sample(...) method of numpy.random.mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    .. note::
        New code should use the ``random`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None`

In [55]:
np.array([2,3,4])

array([2, 3, 4])

In [57]:
b = np.array([[2,3,4], [5,6,7]])

In [59]:
5 * b
b + a

ValueError: ignored

array([[2, 3, 4],
       [5, 6, 7]])

In [68]:
np.random.randint(5, high=50, size= 10, dtype=int)

array([47, 21, 16, 49, 22, 37,  7, 30, 30,  6])

In [76]:
np.random.randint(2, high=10,size = (3,5)) #if high is mentioned then interval will be (0,2)

array([[3, 4, 3, 7, 6],
       [2, 9, 5, 6, 8],
       [4, 7, 7, 8, 6]])

In [77]:
np.random.randint(2,size = (3,5))

array([[0, 0, 1, 0, 1],
       [1, 1, 0, 1, 1],
       [0, 1, 1, 0, 1]])

In [71]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

**`# ATTRIBUTES OF NUMPY`**